[package]
name = "phyra"
version = "0.2.0"
edition = "2021"
license = "GPL-3.0-or-later"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }
uuid = { version = "1", features = ["v4"] }
rfd = "0.15"
zip = { version = "2", default-features = false, features = ["deflate"] }
tempfile = "3"
jsonschema = { version = "0.33", default-features = false }

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
